---
- name: "config : set the hostname"
  hostname:
    name: "{{ hostname }}"
  ignore_errors: true # Can't change hostname when running in Docker container

- name: "config : add hostname to /etc/hosts"
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} Autopilot Hostname"
    block: |
      ::1 {{ hostname }}
      127.0.0.1 {{ hostname }}
    unsafe_writes: yes # Can't use safe writes when running in a Docker container

- name: "config : set the timezone to '{{ timezone }}'"
  timezone:
    name: "{{ timezone }}"

- name: "config : set default home dir permission"
  lineinfile:
    path: /etc/adduser.conf
    regexp: "^DIR_MODE="
    line: "DIR_MODE=0711"
