---
- name: "lsphp73 : install packages"
  apt:
    pkg:
      - lsphp73
      - lsphp73-common
      - lsphp73-curl
      - lsphp73-dbg
      - lsphp73-dev
      - lsphp73-igbinary
      - lsphp73-imagick
      - lsphp73-imap
      - lsphp73-intl
      - lsphp73-ioncube
      - lsphp73-json
      - lsphp73-mysql
      - lsphp73-opcache
      - lsphp73-redis
    state: present
    update_cache: no
  notify: restart lshttpd

- name: "lsphp73 : generate ini configuration"
  template:
    src: php_ini_config.j2
    dest: /usr/local/lsws/lsphp73/etc/php/7.3/mods-available/10-sitepilot.ini
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart lshttpd

- name: "lsphp73 : create php73 symbolic link"
  file:
    src: /usr/local/lsws/lsphp73/bin/php
    dest: /usr/local/bin/php73
    state: link
