---
- name: "swap : manage swap file entry in fstab"
  mount:
    name: none
    src: "{{ swap_path }}"
    fstype: swap
    opts: sw
    state: "present"

- name: "swap : ensure swap file exists"
  command: >
    fallocate -l {{ swap_size }} {{ swap_path }}
  args:
    creates: "{{ swap_path }}"
  register: swap_file_create

- name: "swap : set permissions on swap file"
  file:
    path: "{{ swap_path }}"
    owner: root
    group: root
    mode: "0600"
  when: swap_file_create is changed

- name: "swap : make swap file if necessary"
  command: mkswap {{ swap_path }}
  when:
    - swap_file_create is changed
  register: mkswap_result

- name: "swap : run swapon on the swap file"
  command: swapon {{ swap_path }}
  when: mkswap_result is changed
  ignore_errors: true # Can't run swapon when filesystem type is btrfs

- name: "swap : set swappiness"
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
  when: mkswap_result is changed
