---
- hosts: "all"
  vars:
    # user: ""
    # site: ""
    path: "/opt/sitepilot/users/{{ user }}/sites/{{ site }}"
    path_vhost: "/usr/local/lsws/conf/vhosts/{{ site }}.conf"
    path_proxy: "/etc/caddy/vhosts/{{ site }}.conf"
    path_fail2ban: "/etc/fail2ban/jail.d/{{ site }}.conf"
  tasks:
    - name: "site/destroy : {{ user }} : {{ site }} : remove site folder"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ path }}"

    - name: "site/destroy : {{ user }} : {{ site }} : remove vhost configuration"
      file:
        path: "{{ path_vhost }}"
        state: absent

    - name: "site/destroy : {{ user }} : {{ site }} : remove proxy configuration"
      file:
        path: "{{ path_proxy }}"
        state: absent

    - name: "site/destroy : {{ user }} : {{ site }} : remove fail2ban configuration"
      file:
        path: "{{ path_fail2ban }}"
        state: absent

    - name: "site/destroy : {{ user }} : {{ site }} : reload web server"
      service:
        name: lshttpd
        state: restarted

    - name: "site/destroy : {{ user }} : {{ site }} : reload proxy server"
      service:
        name: caddy
        state: reloaded

    - name: "site/destroy : {{ user }} : {{ site }} : reload fail2ban"
      service:
        name: fail2ban
        state: reloaded
